# Deploy to GitHub Pages workflow
name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: /bill-tracker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Install dependencies
        run: npm ci
        
      - name: Create data directory and copy data files
        run: |
          mkdir -p public/data
          if [ -f data/bills.json ]; then
            cp data/bills.json public/data/
            echo "Copied bills.json to public/data/"
          else
            echo "Warning: data/bills.json not found, creating empty data file"
            echo "[]" > public/data/bills.json
          fi
          
      - name: Build with Next.js
        run: npm run build
        
      - name: Create .nojekyll file
        run: touch ./out/.nojekyll
        
      - name: Ensure data directory exists in output
        run: |
          mkdir -p out/data
          if [ ! -f out/data/bills.json ]; then
            echo "bills.json not found in output, copying from public/data/"
            cp public/data/bills.json out/data/ || echo "[]" > out/data/bills.json
          fi
          
      - name: Debug output directory
        run: |
          echo "Contents of out directory:"
          ls -la out/
          echo "Checking for data directory:"
          ls -la out/data || echo "Data directory not found, creating it now"
          mkdir -p out/data
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4