# Deploy to GitHub Pages workflow
name: Deploy Next.js site to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create data directory and prepare data files
        run: |
          mkdir -p public/data
          if [ -f data/bills.json ]; then
            cp data/bills.json public/data/
          else
            echo "[]" > public/data/bills.json
          fi
      
      - name: Build with Next.js
        env:
          NEXT_PUBLIC_BASE_PATH: /bill-tracker
        run: npm run build
      
      - name: Create .nojekyll file
        run: touch out/.nojekyll
      
      - name: Copy data to output directory
        run: |
          mkdir -p out/data
          cp public/data/bills.json out/data/ || echo "[]" > out/data/bills.json
      
      # Manual artifact preparation and upload - avoiding upload-pages-artifact action
      - name: Prepare artifact
        run: |
          tar -cvf artifact.tar ./out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: artifact.tar
          if-no-files-found: error
          retention-days: 1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4